import Head from 'next/head'
import { Navbar } from '@/components/Navbar'
import { BottomBar } from '@/components/BottomBar'
import { Chart } from '@/components/Chart'
import { TokenHeader } from '@/components/TokenHeader';
import { TokenInfoTable } from '@/components/TokenInfoTable';
import { Swap } from '@/components/Swap';

export default function Home() {
  return (
    <>
      <Head>
        <title>Broccoliswap</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className="min-h-screen grid grid-rows-[min-content_1fr_min-content]">
        <Navbar />

        <main className="hidden lg:grid">

          <div className="flex flex-row max-h-[calc(100vh-82px)] w-full">
            <div className="flex flex-col w-3/4">
              <div className="h-[10%] w-full">
                <TokenHeader />
              </div>
              <div className="h-[50%] w-full">
                <Chart />
              </div>
              <div className="h-[40%] w-full">
                <TokenInfoTable />
              </div>
            </div>
            <div className="w-1/4">
              <Swap />
            </div>
          </div>

        </main>

        <main className="grid lg:hidden">

          <div className="flex flex-col max-h-[calc(100vh-82px)] h-full w-full">
            <div className="h-[10%] w-full">
              <TokenHeader />
            </div>
            <div className="h-[30%] w-full">
              <Chart />
            </div>
            <div className="h-[40%] w-full">
              <TokenInfoTable />
            </div>
            <div className="h-[20%] w-1/4 mt-3">
              <Swap />
            </div>
          </div>

        </main>

        <BottomBar />
      </main>
    </>
  )
}
