import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Brocolliswap</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main>
        <div className="relative isolate overflow-hidden">
          <div className="py-24 px-6 sm:px-6 sm:py-32 lg:px-8">
            <div className="mx-auto w-full text-center">
              <h2 className="text-4xl  tracking-tight text-white">
                Brocolliswap 🥦
              </h2>
              <div className="mt-10 flex items-center justify-center gap-x-6 text-slate-200">
                A swap aggregator that aggregates over multiple routes to obtain the best price. Coming soon™
              </div>
              <a href="https://dgnx.finance/" target="_blank" rel="noreferrer" className="text-orange-500 leading-7">
                Built by DegenX
              </a>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
