service: broccoliswap
frameworkVersion: '2 || 3'

useDotenv: true

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-api-cloudfront

custom:
  ddb:
    ohlc-table-name: ohlc
    connector-address-table-name: connectorAddress
    swap-link-table-name: swapLink
  corsAllowedOrigin:
    dev: http://localhost:3000
    staging: https://staging.broccoliswap.com
    production: https://broccoliswap.com
  ohlcCacheAge:
    dev: 60
    staging: 60
    production: 86400
  transactionsCacheAge:
    dev: 10
    staging: 60
    production: 60
  swapLinkCacheAge:
    dev: 10
    staging: 60
    production: 7776000

provider:
  name: aws
  region: eu-west-1
  profile: broccoliswap
  stage: dev
  runtime: nodejs18.x

  environment:
    BITQUERY_API_KEY: ${env:BITQUERY_API_KEY}
    MIXPANEL_PROJECT_KEY: ${env:MIXPANEL_PROJECT_KEY}
    DEXTOOLS_API_KEY: ${env:DEXTOOLS_API_KEY}
    OHLC_TABLE_NAME: ${self:custom.ddb.ohlc-table-name}-${opt:stage, 'dev'}
    SWAP_LINK_TABLE_NAME: ${self:custom.ddb.swap-link-table-name}-${opt:stage, 'dev'}
    CONNECTOR_ADDRESS_TABLE_NAME: ${self:custom.ddb.connector-address-table-name}-${opt:stage, 'dev'}
    CORS_ALLOWED_ORIGIN: ${self:custom.corsAllowedOrigin.${opt:stage, self:provider.stage}}
    OHLC_CACHE_AGE: ${self:custom.ohlcCacheAge.${opt:stage, self:provider.stage}}
    TRANSACTIONS_CACHE_AGE: ${self:custom.transactionsCacheAge.${opt:stage, self:provider.stage}}
    SWAP_LINK_CACHE_AGE: ${self:custom.swapLinkCacheAge.${opt:stage, self:provider.stage}}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 
        - "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.ddb.ohlc-table-name}-${opt:stage, 'dev'}*"
        - "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.ddb.connector-address-table-name}-${opt:stage, 'dev'}*"
        - "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.ddb.swap-link-table-name}-${opt:stage, 'dev'}*"

functions:
  ohlcGet:
    handler: ohlc/get.handler
    memorySize: 1024
    timeout: 29
    events:
      - http:
          cors: true
          path: /ohlc/{chain}/{tokenAddress}/{from}/{to}/{resolution}/{countBack}
          method: get
          request:
            parameters:
              paths:
                chain: true
                tokenAddress: true
                from: true
                to: true
                resolution: true
                countBack: true

  recentTransactionsGet:
    handler: transactions/get.handler
    memorySize: 1024
    timeout: 29
    events:
      - http:
          cors: true
          path: /transactions/{chain}/{tokenAddress}
          method: get
          request:
            parameters:
              paths:
                chain: true
                tokenAddress: true

  track:
    handler: track/post.handler
    memorySize: 1024
    timeout: 29
    events:
      - http:
          cors: true
          path: /track
          method: post

  putSwapLink:
    handler: swapLink/put.handler
    memorySize: 1024
    timeout: 29
    events:
      - http:
          cors: true
          path: /swapLink
          method: post

  getSwapLink:
    handler: swapLink/get.handler
    memorySize: 1024
    timeout: 29
    events:
      - http:
          cors: true
          path: /swapLink/{link}
          method: get
          request:
            parameters:
              paths:
                link: true

  getBridgeTxInfo:
    handler: transactions/getBridgeTxInfo.handler
    memorySize: 1024
    timeout: 29
    events:
      - http:
          cors: true
          path: /getBridgeTxInfo/{address}/{toChain}/{hash}
          method: get
          request:
            parameters:
              paths:
                address: true
                toChain: true
                hash: true

  dexToolsPair:
    handler: dextools/pair.handler
    memorySize: 1024
    timeout: 29
    events:
      - http:
          cors: true
          path: /dextools/pair/{chain}/{address}
          method: get
          request:
            parameters:
              paths:
                chain: true
                address: true

  dexToolsToken:
    handler: dextools/token.handler
    memorySize: 1024
    timeout: 29
    events:
      - http:
          cors: true
          path: /dextools/token/{chain}/{address}
          method: get
          request:
            parameters:
              paths:
                chain: true
                address: true

resources:
  Resources:
    TranslationsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.ddb.ohlc-table-name}-${opt:stage, 'dev'}
        AttributeDefinitions:
          - AttributeName: chainTokenResolution
            AttributeType: S
          - AttributeName: time
            AttributeType: N
        KeySchema:
          - AttributeName: chainTokenResolution
            KeyType: HASH
          - AttributeName: time
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    ConnectorAddressTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.ddb.connector-address-table-name}-${opt:stage, 'dev'}
        AttributeDefinitions:
          - AttributeName: chain
            AttributeType: S
          - AttributeName: token
            AttributeType: S
        KeySchema:
          - AttributeName: chain
            KeyType: HASH
          - AttributeName: token
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    SwapLinkTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.ddb.swap-link-table-name}-${opt:stage, 'dev'}
        AttributeDefinitions:
          - AttributeName: link
            AttributeType: S
        KeySchema:
          - AttributeName: link
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
